### ISSUE TITLE
Opening T19 Detail, SoulissApp Crash

### ISSUE THREAD

**Issue by marcolino7** [souliss/soulissapp#77] opened 2015-10-01 07:55 UTC
Opening a T19 detail to access slide for luminosity or music sync, the app crash.
Let me know if and what more detail needed.
Marco

**Comment by shineangelic** [comment] 2015-10-04 10:48
have you sent the report via android? It seems that other people can use it, maybe it's something related to your device/version and a stacktrace would help :)

**Comment by marcolino7** [comment] 2015-10-19 08:07
Hi,
It happen also on new Souliss APP  version, it happen on my S4 (KitKat) and Note3 (Lollipop), both with Samsung Firmware. When app crash do not ask me for send the crash report.
Let me know how to get stacktrace and other logs you need. I'm available to help you.

Marco

**Comment by shineangelic** [comment] 2015-10-19 12:28
of course the stackstrace of the error would help me greatly: the problem is that I'm not able to reproduce it. It's probably a stupid mistake I made, but I need the log to understand it

**Comment by marcolino7** [comment] 2015-10-19 12:30
Hi Alessando,
I don't know whatis and how capture stacktrace. If you can help me, I can reproduce and capture.

Marco

**Comment by shineangelic** [comment] 2015-10-19 12:37
We can start looking ionside your /Souliss folder inside SdCard...It should contain the App's log. Let's have a look

**Comment by marcolino7** [comment] 2015-10-19 12:43
Ciao Alessando,
I reproduced the issue, on Italian Lollipop Crash report is called "Cronaca", and I just sent one to google, I hope you can retrieve it. Meanwhile a deleted souliss.log an created a new one reproducing the issue. It is here attached.
Let me know what else you need.

Marco
[souliss.txt](https://github.com/souliss/soulissapp/files/15987/souliss.txt)

**Comment by shineangelic** [comment] 2015-10-19 12:51
The included log doesn't contain any error. Now I'll check in Play console if I received your report. Thank you, we'll fix this :)

**Comment by shineangelic** [comment] 2015-10-19 13:40
It arrived now!!! It's a problem with Fourier:

android.view.InflateException: Binary XML file line #179: Error inflating class com.pheelicks.visualizer.VisualizerView
    at android.view.LayoutInflater.createView(LayoutInflater.java:640)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:668)
    at android.view.LayoutInflater.inflate(<Xposed>)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
    at it.angelic.soulissclient.fragments.T19SingleChannelLedFragment.onCreateView(T19SingleChannelLedFragment.java:168)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1965)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5942)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
    at android.view.LayoutInflater.createView(LayoutInflater.java:614)
    ... 27 more
Caused by: java.lang.RuntimeException: Cannot initialize Visualizer engine, error: -4
    at android.media.audiofx.Visualizer.<init>(Visualizer.java:216)
    at com.pheelicks.visualizer.VisualizerView.b(VisualizerView.java:82)
    at com.pheelicks.visualizer.VisualizerView.<init>(VisualizerView.java:58)
    at com.pheelicks.visualizer.VisualizerView.<init>(VisualizerView.java:62)
    ... 30 more

**Comment by shineangelic** [comment] 2015-10-19 13:40
are you using xPosed?

**Comment by marcolino7** [comment] 2015-10-19 13:40
Yes

**Comment by shineangelic** [comment] 2015-10-19 13:45
azz. The problem comes from there. The Visualizer we're using for music mode (loaded when T19 panel is shown)seems not compatible with xposed

**Comment by shineangelic** [comment] 2015-10-19 13:47
here it is!!

https://github.com/felixpalmer/android-visualizer/issues/5

I'm sorry this is the cause of your problem and it will be very difficult to fix it as it's not in code I wrote :(

**Comment by marcolino7** [comment] 2015-10-19 13:51
Reading, seems that it could be related to Music Sync on Souliss APP.
You could detect this exception and disable music sync. There is a lot of Samsung Device.....

**Comment by shineangelic** [comment] 2015-10-19 13:55
I will try to do something, but I guess the problem is more related to xposed than to Samsung device itself. 

Basically, xposed doesn't know the Visualizer used during music sync. Can you disable it temporarily in order to confirm my guess?

**Comment by marcolino7** [comment] 2015-10-19 14:08
I cannot disable Xposed, on lollipo and samsung is flash in recovery, but tried on my Samsung TAB S and work.

**Comment by marcolino7** [comment] 2015-10-26 21:08
Ciao Alessandro,
I can confirm that issue is still present on RGB strip control

**Comment by andrempo** [comment] 2015-11-21 18:05
Same problem with stock Moto X 2014.

**Comment by andrempo** [comment] 2015-11-21 21:09
That is Android 6 problem from the new permission system. To record audio you also need to ask for that permission to the user. 
 http://stackoverflow.com/questions/33494631/android-visualizer-error-only-in-android-6-0

It works if you go to AppInfo for this app; navigate to permissions and allow Microphone

**Comment by shineangelic** [comment] 2016-02-22 17:39
yes, thank you @andrempo 
I shall find a way to explicitly ask for that permission on MM. Since it's an external lib

**Comment by shineangelic** [comment] 2016-02-22 21:29
BTW,  @marcolino7 only ited (KitKat) and Note3 (Lollipop) so this remains strange

**Comment by shineangelic** [comment] 2016-03-08 18:56
should be fixed in 1.7.0

**Closed as completed by shineangelic** 2016-03-08 18:56 UTC
Labels: bug
